DROP OWNED BY api;
DROP ROLE IF EXISTS api;

CREATE ROLE api
LOGIN
PASSWORD 'api';

REVOKE ALL ON SCHEMA public FROM public;

REVOKE ALL PRIVILEGES 
ON DATABASE dev2dev 
FROM api;

GRANT USAGE ON SCHEMA public 
TO api;

GRANT SELECT, UPDATE, INSERT, DELETE
ON ALL TABLES
IN SCHEMA "public"
TO api;

ALTER DEFAULT PRIVILEGES FOR ROLE dbinit
IN SCHEMA "public" 
GRANT SELECT, UPDATE, INSERT, DELETE 
ON TABLES 
TO api;