DROP OWNED BY dbinit;
DROP ROLE IF EXISTS dbinit;

CREATE ROLE dbinit
LOGIN
PASSWORD 'dbinit';

REVOKE ALL ON SCHEMA public FROM public;

REVOKE ALL PRIVILEGES 
ON DATABASE dev2dev 
FROM dbinit;

GRANT USAGE ON SCHEMA public 
TO dbinit;

--ALTER DATABASE dev2dev
--OWNER TO dbinit;

GRANT CREATE
ON SCHEMA "public"
TO dbinit;

GRANT REFERENCES ON ALL TABLES
IN SCHEMA "public"
TO dbinit;

REVOKE SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES
IN SCHEMA "public"
FROM dbinit;

ALTER DEFAULT PRIVILEGES FOR ROLE dbinit
IN SCHEMA "public"
REVOKE SELECT, INSERT, UPDATE, DELETE 
ON TABLES 
FROM dbinit;
